var principal = [
  {
    id: 1,
    Nombre: "Milanesas",
    carne: {
      ing: "Bola de lomo",
      ing: "Nalga",
    },
    pollo: {
      ing: "Pechuga",
      ing: "Suprema",
    },
    vegetal: {
      ing: "Berenjenas",
      ing: "Zuchinni",
      ing: "Zapallitos",
      ing: "Calabaza",
    },
    ing: "Pan rallado",
    ing: "Huevos",
  },
  {
    id: 6,
    Nombre: "Omelette",
    ing: "Huevos",
    ing: "Jamón",
    ing: "Queso",
    ing: "Aceitunas",
    ing: "Tomates",
  },
  {
    id: 7,
    Nombre: "Hamburguesas",
    carne: {
      ing: "Carne picada",
    },
  },
  {
    id: 11,
    Nombre: "Pastas",
    ing: "Fideos",
    ing: "Ravioles",
    ing: "Noquis",
  },
  {
    id: 13,
    Nombre: "Tarta",
    carne: {
      ing: "Jamón",
    },
    pescado: {
      ing: "Atún",
    },
    pollo: {
      ing: "Pollo",
    },
    ing: "Queso",
    ing: "Zapallitos",
    ing: "Puerro",
    ing: "Calabaza",
    ing: "Espinaca",
    ing: "Choclo",
    ing: "Acelga",
    ing: "Brócoli",
  },
];
var acompañamiento = [
  {
    id: 2,
    Nombre: "Papas al horno",
    ing: "Papas",
  },
  {
    id: 3,
    Nombre: "Puré",
    ing: "Papas",
  },
  {
    id: 4,
    Nombre: "Papas fritas",
    ing: "Papas",
  },
  {
    id: 5,
    Nombre: "Ensalada rusa",
    ing: "Papas",
    ing: "Huevo",
    ing: "Zanahoria",
    ing: "Arvejas",
    ing: "Mayonesa",
  },
  {
    id: 10,
    Nombre: "Ensalada",
    ing: "Tomate",
    ing: "Lechuga",
    ing: "Zanahoria",
    ing: "Cebolla",
    ing: "Choclo",
    ing: "Palta",
    ing: "Manzana",
    ing: "Rúcula",
    ing: "Radicheta",
    ing: "Ajo",
    ing: "Limón",
    ing: "Pollo"
  },
  {
    id: 12,
    Nombre: "Salsa Filetto",
    ing: "Tomate",
    ing: "Ajo",
    ing: "Albahaca",
    ing: "Ketchup",
  },
  {
    id: 15,
    Nombre: "Salsa Blanca",
    ing: "Harina",
    ing: "Leche",
    ing: "Manteca",
    ing: "Maicena",
  },
  {
    id: 16,
    Nombre: "Crema",
    ing: "Crema",
    ing: "Cebolla",
    ing: "Cebolla de verdeo",
    ing: "Champiniones",
    ing: "Aceitunas negras",
    ing: "Leche",
  },
  {
    id: 17,
    Nombre: "Salsa de queso",
    ing: "Queso azul",
    ing: "Leche",
    ing: "Maicena",
    ing: "Cebolla",
    ing: "Queso en hebras",
  },
  {
    id: 20,
    Nombre: "Salsa de puerro y verdeo",
    ing: "Puerros",
    ing: "Cebolla de verdeo",
    ing: "Ajo",
    ing: "Crema",
    ing: "Queso en hebras",
  },
  {
    id: 14,
    Nombre: "Guacamole",
    ing: "Palta",
    ing: "Morrón",
    ing: "Cebolla",
    ing: "Tomate",
    ing: "Limón",
  },
  {
    id: 21,
    Nombre: "Ensalada capresse",
    ing: "Tomate",
    ing: "Albahaca",
    ing: "Queso mozzarella",
  },
];
